# Feature Engineering starter - delete non related column and feature selection 
# Identify feature and target column and split them 
# Train Test Split 
# Missing values handling 
# outliers detection and handling (delete or cap them)
# Categorical column encoding 
# Scaling Numerical values 
# Feature creation

In [14]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
from sklearn.model_selection import train_test_split

In [15]:
df = pd.read_csv('titanic_data_updated.csv') 
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,no,third,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,yes,first,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,yes,third,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,yes,first,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,no,third,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,no,second,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,yes,first,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,no,third,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,yes,first,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,no,third,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [16]:
df.drop(['PassengerId','Name','Ticket'],axis=1,inplace=True)

In [17]:
df

    Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         no   third    male  22.0      1      0   7.2500   NaN        S
1        yes   first  female  38.0      1      0  71.2833   C85        C
2        yes   third  female  26.0      0      0   7.9250   NaN        S
3        yes   first  female  35.0      1      0  53.1000  C123        S
4         no   third    male  35.0      0      0   8.0500   NaN        S
..       ...     ...     ...   ...    ...    ...      ...   ...      ...
886       no  second    male  27.0      0      0  13.0000   NaN        S
887      yes   first  female  19.0      0      0  30.0000   B42        S
888       no   third  female   NaN      1      2  23.4500   NaN        S
889      yes   first    male  26.0      0      0  30.0000  C148        C
890       no   third    male  32.0      0      0   7.7500   NaN        Q

[891 rows x 9 columns]

In [18]:
# missing values
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Cabin       687
Embarked      2
dtype: int64

In [19]:
df.drop(['Cabin'],axis=1,inplace=True)

In [20]:
df

    Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         no   third    male  22.0      1      0   7.2500        S
1        yes   first  female  38.0      1      0  71.2833        C
2        yes   third  female  26.0      0      0   7.9250        S
3        yes   first  female  35.0      1      0  53.1000        S
4         no   third    male  35.0      0      0   8.0500        S
..       ...     ...     ...   ...    ...    ...      ...      ...
886       no  second    male  27.0      0      0  13.0000        S
887      yes   first  female  19.0      0      0  30.0000        S
888       no   third  female   NaN      1      2  23.4500        S
889      yes   first    male  26.0      0      0  30.0000        C
890       no   third    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [23]:
# x er bhitor amra features raki 
X = df.drop(['Survived'],axis=1)
X

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0     third    male  22.0      1      0   7.2500        S
1     first  female  38.0      1      0  71.2833        C
2     third  female  26.0      0      0   7.9250        S
3     first  female  35.0      1      0  53.1000        S
4     third    male  35.0      0      0   8.0500        S
..      ...     ...   ...    ...    ...      ...      ...
886  second    male  27.0      0      0  13.0000        S
887   first  female  19.0      0      0  30.0000        S
888   third  female   NaN      1      2  23.4500        S
889   first    male  26.0      0      0  30.0000        C
890   third    male  32.0      0      0   7.7500        Q

[891 rows x 7 columns]

In [22]:
# target column 
y = df['Survived'] 
y

0       no
1      yes
2      yes
3      yes
4       no
      ...
886     no
887    yes
888     no
889    yes
890     no
Name: Survived, Length: 891, dtype: object

# Train Test Split

In [24]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [27]:
X_train

     Pclass     Sex   Age  SibSp  Parch      Fare Embarked
331   first    male  45.5      0      0   28.5000        S
733  second    male  23.0      0      0   13.0000        S
382   third    male  32.0      0      0    7.9250        S
704   third    male  26.0      1      0    7.8542        S
813   third  female   6.0      4      2   31.2750        S
..      ...     ...   ...    ...    ...       ...      ...
106   third  female  21.0      0      0    7.6500        S
270   first    male   NaN      0      0   31.0000        S
860   third    male  41.0      2      0   14.1083        S
435   first  female  14.0      1      2  120.0000        S
102   first    male  21.0      0      1   77.2875        S

[712 rows x 7 columns]

In [28]:
display(y_train)

331     no
733     no
382     no
704     no
813     no
      ...
106    yes
270     no
860     no
435    yes
102     no
Name: Survived, Length: 712, dtype: object

In [29]:
X_test

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
709   third    male   NaN      1      1  15.2458        C
439  second    male  31.0      0      0  10.5000        S
840   third    male  20.0      0      0   7.9250        S
720  second  female   6.0      0      1  33.0000        S
39    third  female  14.0      1      0  11.2417        C
..      ...     ...   ...    ...    ...      ...      ...
433   third    male  17.0      0      0   7.1250        S
773   third    male   NaN      0      0   7.2250        C
25    third  female  38.0      1      5  31.3875        S
84   second  female  17.0      0      0  10.5000        S
10    third  female   4.0      1      1  16.7000        S

[179 rows x 7 columns]

In [30]:
y_test

709    yes
439     no
840     no
720    yes
39     yes
      ...
433     no
773     no
25     yes
84     yes
10     yes
Name: Survived, Length: 179, dtype: object

# Imputing missing values

In [31]:
# for normal distribution use mean 
# for skewed data use Median 
# for categorical we use Mode

# Imputing Numerical Features

In [32]:
# pandas fill na 
# ML way to fill -- simple imputer

In [34]:
X_train.isnull().sum()

Pclass        0
Sex           0
Age         140
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [35]:
X_test.isnull().sum()

Pclass       0
Sex          0
Age         37
SibSp        0
Parch        0
Fare         0
Embarked     0
dtype: int64

In [36]:
age_mean= X_train['Age'].mean()
age_mean

np.float64(29.498846153846156)

In [41]:
X_train['age_mean_imputer'] = X_train['Age'].fillna(age_mean) 
X_test['age_mean_imputer'] = X_train['Age'].fillna(age_mean)

In [40]:
X_train.isnull().sum()

Pclass                0
Sex                   0
Age                 140
SibSp                 0
Parch                 0
Fare                  0
Embarked              2
age_mean_imputer      0
dtype: int64